/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ac_constants.h"

namespace algo_cloud_base {

const acConstants g_ac_constants;

acConstants::acConstants() {
}

} // namespace

