/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ac_CONSTANTS_H
#define ac_CONSTANTS_H

#include "ac_types.h"

namespace algo_cloud_base {

class acConstants {
 public:
  acConstants();

};

extern const acConstants g_ac_constants;

} // namespace

#endif
